async function load(){
  let id=new URLSearchParams(location.search).get('id');
  shell('contracts','Contract details','Source-backed contract intelligence.');
  if(!id){document.querySelector('#content').innerHTML='<div class="card"><div class="notice">No contract ID was provided.</div></div>';return}
  let c=await api('/contracts/'+id);
  if(c.status&&c.status!=='completed'){
    document.querySelector('#content').innerHTML=`<div class="card"><div class="upload-processing active"><div class="processing-spinner"></div><div class="processing-content"><div class="processing-title">${c.status==='failed'?'Analysis failed':'Contract is still processing'}</div><div class="processing-status">${esc(c.error||'Text extraction and AI analysis are running in the background. Refresh in a moment.')}</div></div></div><a class="btn secondary" style="margin-top:16px" href="/pages/contracts.html">Back to contracts</a></div>`;
    return;
  }
  document.querySelector('#content').innerHTML=`<div class="grid two"><div class="card"><div class="kpi">CONTRACT</div><h2>${esc(c.name)}</h2><p class="muted">${esc(c.filename)}</p><div class="grid three"><div><div class="kpi">Effective</div><b>${fmt(c.effective)}</b></div><div><div class="kpi">Expires</div><b>${fmt(c.expires)}</b></div><div><div class="kpi">Parties</div><b>${c.parties.length}</b></div></div></div><div class="card"><h3>AI summary</h3><p>${esc(c.summary)}</p></div></div><div class="grid three" style="margin-top:16px"><div class="card"><div class="kpi">PAYMENT</div><p>${esc(c.payment)}</p></div><div class="card"><div class="kpi">RENEWAL</div><p>${esc(c.renewal)}</p></div><div class="card"><div class="kpi">TERMINATION</div><p>${esc(c.termination)}</p></div></div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Obligations</h3>${c.obligations.map(o=>`<div class="source"><b>${esc(o.description)}</b><div class="kpi">${esc(o.party)} · ${fmt(o.deadline)} · ${esc(o.frequency)}</div><span class="badge ${String(o.risk||'Medium').toLowerCase()}">${esc(o.risk)} risk</span><div class="kpi">§${esc(o.section)} · Page ${o.page}</div></div>`).join('')||'<p class="muted">No obligations extracted.</p>'}</div><div class="card"><h3>Indexed clauses</h3>${c.clauses.map(x=>`<div class="source"><b>${esc(x.type)} · §${esc(x.section)}</b><p>${esc(x.text)}</p><div class="kpi">Page ${x.page}</div></div>`).join('')||'<p class="muted">No indexed clauses.</p>'}</div></div>`
}
load().catch(e=>{document.querySelector('#content').innerHTML=`<div class="card"><div class="notice">${esc(e.message)}</div></div>`});
